 development:
   adapter: postgresql
   encoding: unicode
   reconnect: false
   port: 5432
   username: postgres
   password: password
   database: assignment_db_development
   pool: 5
   host: localhost
   

